name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./server-query/requirements.txt
          pip install -r ./server-collext_data/requirements.txt
      
      # Run pytest
      - name: Run Tests
        run: 

  deploy:
    name: Build and Deploy Docker
    needs: test # 'test' job이 성공해야만 실행됨
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: |
          docker build -t syhan655/dev5ps:latest .
      
      - name: Push Docker Image
        run: |
          docker push syhan655/dev5ps:latest

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.11
        with:
          host: ${{ secrets.SERVER_IP }}  # 서버 IP 주소
          username: ${{ secrets.SERVER_USERNAME  }}     # SSH 사용자 이름
          key: ${{ secrets.SSH_KEY }}  # SSH 비밀 키
          script: |
            docker-compose down
            docker-compose up build
          

